# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Concept.create(title: "self driving cars")
Concept.create(title: "In N Out Burger")
Concept.create(title: "hiking")
Concept.create(title: "horror movies")
Concept.create(title: "Justin Bieber")
Concept.create(title: "housework")
Concept.create(title: "talking about movies after they're over")
Concept.create(title: "dogs")
Concept.create(title: "cronuts")
Concept.create(title: "TSA")
Concept.create(title: "modern art")
Concept.create(title: "marathons")
Concept.create(title: "Bey aka Beyonce")
Concept.create(title: "SF Giants")
Concept.create(title: "children")
Concept.create(title: "Texas")
Concept.create(title: "cross fit")
Concept.create(title: "museums")
Concept.create(title: "Michael Jackson")
Concept.create(title: "pumpkin spice lattes")
Concept.create(title: "cooking")
Concept.create(title: "composting")
Concept.create(title: "traveling alone")
Concept.create(title: "Comcast")
Concept.create(title: "Apple watches")
Concept.create(title: "dirty martinis")
Concept.create(title: "cats")
Concept.create(title: "cat videos")
Concept.create(title: "dumpster diving")
Concept.create(title: "Stanford")
Concept.create(title: "skiing")
Concept.create(title: "old people")
Concept.create(title: "keg stands")
Concept.create(title: "Taylor Swift")
Concept.create(title: "Settlers of Catan")
Concept.create(title: "organic food")
Concept.create(title: "legalized pot")
Concept.create(title: "planking")
Concept.create(title: "blind dates")
Concept.create(title: "arts/crafts")
Concept.create(title: "unitards")
Concept.create(title: "chocolate")
Concept.create(title: "Donald Trump")
Concept.create(title: "chicken and waffles")
Concept.create(title: "gun ranges")
Concept.create(title: "massages")
Concept.create(title: "romance novels")
Concept.create(title: "Orange is the New Black")
Concept.create(title: "beards")
Concept.create(title: "reality TV")
Concept.create(title: "talking on the phone")
Concept.create(title: "musicals")
Concept.create(title: "Julia Childs")
Concept.create(title: "Las Vegas")
Concept.create(title: "shopping")
Concept.create(title: "beer pong")
Concept.create(title: "winter")
Concept.create(title: "recycling")
Concept.create(title: "McDonalds")
Concept.create(title: "Occupy Wall Street")
Concept.create(title: "learning a language")
Concept.create(title: "Bernie Sanders")
Concept.create(title: "traveling abroad")
Concept.create(title: "Chinese food")
Concept.create(title: "trying out new things")
Concept.create(title: "Oktoberfest")
Concept.create(title: "Valentine's Day")
Concept.create(title: "Valentine's Day all alone")
Concept.create(title: "public transportation")
Concept.create(title: "dog outfits")
Concept.create(title: "golf")
Concept.create(title: "Che Guevara")
Concept.create(title: "writing letters")
Concept.create(title: "toilet paper with the paper hanging in the front")
Concept.create(title: "gardening")
Concept.create(title: "getting blood taken")
Concept.create(title: "stand up comedy")
Concept.create(title: "writing")
Concept.create(title: "plaid shirts")
Concept.create(title: "papaya")
Concept.create(title: "painting")
Concept.create(title: "Apple computers")
Concept.create(title: "reclaimed wood")
Concept.create(title: "Napster")
Concept.create(title: "metal rock")
Concept.create(title: "Windows XP")
Concept.create(title: "brussel sprouts")
Concept.create(title: "Star Wars")
Concept.create(title: "dancing")
Concept.create(title: "tattoos")
Concept.create(title: "Silicon Valley")
Concept.create(title: "board games")
Concept.create(title: "independent film")
Concept.create(title: "zumba")
Concept.create(title: "volunteer work")
Concept.create(title: "Berkeley")
Concept.create(title: "Santa Claus")
Concept.create(title: "Head2Head")
Concept.create(title: "spin class")
Concept.create(title: "computer games")
Concept.create(title: "extreme sports")
Concept.create(title: "the Mission")
Concept.create(title: "capitalism")
Concept.create(title: "raw seafood")
Concept.create(title: "Star Trek")
Concept.create(title: "man buns")
Concept.create(title: "Volkswagon")
Concept.create(title: "France")
Concept.create(title: "brainstorming new ideas")
Concept.create(title: "casual Fridays")
Concept.create(title: "Fashion Week")
Concept.create(title: "nice guys")
Concept.create(title: "Harry Potter")
Concept.create(title: "nude beaches")
Concept.create(title: "rain storms")
Concept.create(title: "iPads")
Concept.create(title: "carwashes")
Concept.create(title: "socialism")
Concept.create(title: "listening")
Concept.create(title: "50 Shades of Gray")
Concept.create(title: "tiny houses")
Concept.create(title: "Excel modeling")
Concept.create(title: "calling mom")
Concept.create(title: "eating alone")
Concept.create(title: "tasting menus")
Concept.create(title: "peanuts")
Concept.create(title: "picnics")
Concept.create(title: "treehouses")
Concept.create(title: "HDTV")
Concept.create(title: "China")
Concept.create(title: "high school reunions")
Concept.create(title: "Empire")
Concept.create(title: "James Bond")
Concept.create(title: "Hillary Clinton")
Concept.create(title: "thinking aloud")
Concept.create(title: "preemptive war")
Concept.create(title: "Los Angeles")
Concept.create(title: "surprise birthday parties")
Concept.create(title: "flowers from a friend")
Concept.create(title: "Mean Girls")
Concept.create(title: "How to Get Away with Murder")
Concept.create(title: "singing in the shower")
Concept.create(title: "The New Yorker")
Concept.create(title: "Anthony Bourdain")
Concept.create(title: "hostels")
Concept.create(title: "fitbits")
Concept.create(title: "mindfulness")
Concept.create(title: "The Book of Mormon")
Concept.create(title: "suburbs")
Concept.create(title: "Google Glass")
Concept.create(title: "cilantro")
Concept.create(title: "star gazing")
Concept.create(title: "food fights")
Concept.create(title: "Britney Spears")
Concept.create(title: "Black Friday")
Concept.create(title: "Seinfeld")
Concept.create(title: "minimalism")
Concept.create(title: "Internet Explorer")
Concept.create(title: "scrapbooking")
Concept.create(title: "Shakespeare")
Concept.create(title: "rom coms")
Concept.create(title: "spicy food")
Concept.create(title: "volunteering")
Concept.create(title: "Grateful Dead")
Concept.create(title: "Barack Obama")
Concept.create(title: "Halloween")
Concept.create(title: "playing it safe")
Concept.create(title: "social security")
Concept.create(title: "police")
Concept.create(title: "planes")
Concept.create(title: "Edward Snowden")
Concept.create(title: "liver and onions")
Concept.create(title: "home videos")
Concept.create(title: "working with others")
Concept.create(title: "IPA beer")
Concept.create(title: "summer")
Concept.create(title: "United Nations")
Concept.create(title: "Obamacare")
Concept.create(title: "tolls on bridges")
Concept.create(title: "bars without signs out front")
Concept.create(title: "Arnold Swartzenneger")
Concept.create(title: "nacho hats")
Concept.create(title: "Calvin and Hobbes")
Concept.create(title: "beer brewing")
Concept.create(title: "ballet")
Concept.create(title: "writing poetry")
Concept.create(title: "chocolate ice cream")
Concept.create(title: "Coldplay")
Concept.create(title: "Machiovelli")
Concept.create(title: "finance")
Concept.create(title: "Jonas Brothers")
Concept.create(title: "avocados")
Concept.create(title: "NPR")
Concept.create(title: "investing")


Game.create(title: "Gryffindor")
Game.create(title: "Hufflepuff")
Game.create(title: "Ravenclaw")
Game.create(title: "Slytherin")
Game.create(title: "Stanford")
Game.create(title: "Friends")
Game.create(title: "Bay Area Youngsters (BAY)")
Game.create(title: "Draw Group")
Game.create(title: "Family")
Game.create(title: "Best Study Group")
Game.create(title: "Group1")




