# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Concept.create(title: "self driving cars", image: "http://blogs-images.forbes.com/sethporges/files/2014/05/googlecar-e1401261602733.jpg")
Concept.create(title: "In N Out Burger", image: "http://assets3.thrillist.com/v1/image/1185257/size/tl-horizontal_main/13-things-you-didn-t-know-about-in-n-out-burger")
Concept.create(title: "hiking", image: "http://www.michigan.org/blog/wp-content/uploads/hiking-in-michigan.jpg")
Concept.create(title: "horror movies", image: "http://vignette1.wikia.nocookie.net/chuckychildsplay/images/d/dc/The-Killer-Chucky-Doll-Photo.jpg/revision/latest?cb=20140121205042")
Concept.create(title: "Justin Bieber", image: "http://cdn.thewire.com/media/img/upload/wire/2014/08/05/RTR3ALA9-1/lead_large.jpg")
Concept.create(title: "housework", image: "http://cdn.abclocal.go.com/content/creativecontent/images/cms/389039_1280x720.jpg")
Concept.create(title: "talking about movies after they're over", image: "http://www.leisure-exchange.co.uk/assets/galleries/3da90c9e-cf88-4087-87ec-f3f182b77aa3/main/Cinema.jpg")
Concept.create(title: "dogs", image: "http://www.zastavki.com/pictures/originals/2013/Animals___Dogs_Beagle_dog_lying_on_a_white_background_049935_.jpg")
Concept.create(title: "Starbucks", image: "http://anthropologyworks.com/wp-content/uploads/2012/04/starbucks.jpg")
Concept.create(title: "TSA", image: "https://cbssanfran.files.wordpress.com/2010/11/tsa_patdown_107077228.jpg?w=420")
Concept.create(title: "modern art", image: "http://si.wsj.net/public/resources/images/OB-VI915_SOTHEB_DV_20121114021550.jpg")
Concept.create(title: "marathons", image: "http://media1.fdncms.com/charleston/imager/got-questions-for-the-ridiculously-photogenic-bridge-runner/u/slideshow/4049187/runner-t.jpg")
Concept.create(title: "Bey aka Beyonce", image: "http://assets-s3.usmagazine.com/uploads/assets/article_photos/454112254_Beyonce-467.jpg")
Concept.create(title: "New York Yankees", image: "http://nysfop46.org/wp-content/uploads/2015/05/Yankeelogo.jpg")
Concept.create(title: "Airbnb", image: "https://daveakshay.files.wordpress.com/2014/10/airbnb-new-logo-automation-logo-1.jpg")
Concept.create(title: "children", image: "http://mvymca.org/sites/default/files/pictures/Kids.jpg")
Concept.create(title: "Texas", image: "http://guideimg.alibaba.com/images/shop/86/11/07/7/texas-playing-cards-don-t-mess-flag-texas-souvenirs-texas-souvenir_311917.jpg")
Concept.create(title: "cross fit", image: "http://sweatrxmag.com/newsite/wp-content/uploads/2013/07/jay-lacey-3-1_.jpg")
Concept.create(title: "cats", image: "http://s.hswstatic.com/gif/whiskers-sam.jpg")
Concept.create(title: "cat videos", image: "http://cdn2.hellogiggles.com/wp-content/uploads/2014/06/30/computer-cat.jpg")
Concept.create(title: "steak", image: "https://chicolockersausage.files.wordpress.com/2012/01/grilled-rare-steak.jpg")
Concept.create(title: "Michael Jackson", image: "http://www.michaeljackson.com/sites/mjackson/files/MICHAEL-JACKSON-BAD-ALBUM-MINI-POSTER-pam31934.jpg")
Concept.create(title: "pumpkin pie", image: "http://cookdiary.net/wp-content/uploads/images/PUMPKIN-PIE_16585.jpg")
Concept.create(title: "cooking", image: "http://chefsequipmentemporium.com/chefs/wp-content/uploads/2014/12/Wok-Cooking.jpg")
Concept.create(title: "Pikachu", image: "http://vignette1.wikia.nocookie.net/characters/images/f/fc/025Pikachu_OS_anime_5.png/revision/latest?cb=20141229045147")
Concept.create(title: "traveling alone", image: "http://www.foodtravelworld.com/wp-content/uploads/2014/10/travelling-alone.jpg")
Concept.create(title: "Game of Thrones", image: "http://i1.wp.com/www.metalinjection.net/wp-content/uploads/2014/04/Game-of-Thrones-metal.jpg?fit=750%2C1000")
Concept.create(title: "Google glass", image: "http://cdn.arstechnica.net/wp-content/uploads/2014/01/google-glass-glasses-640x343.jpg")
Concept.create(title: "martinis", image: "http://liquor.com/wp-content/uploads/2011/04/Dirty-Martini-newest.jpg")
Concept.create(title: "dumpster diving")
Concept.create(title: "high school", image: "http://www.slate.com/content/dam/slate/blogs/xx_factor/2013/high%20school.jpg.CROP.rectangle3-large.jpg")
Concept.create(title: "skiing", image: "http://i.telegraph.co.uk/multimedia/archive/01784/off-piste620_1784286a.jpg")
Concept.create(title: "old people", image: "http://mash10.com/wp-content/uploads/sites/48/2015/01/Old-people-playing-on-the-Gamecube.jpg")
Concept.create(title: "whiskey", image: "http://laughingsquid.com/wp-content/uploads/2014/04/Ice-Chair.png")
Concept.create(title: "Taylor Swift")
Concept.create(title: "Settlers of Catan")
Concept.create(title: "organic food")
Concept.create(title: "legalized pot")
Concept.create(title: "planking")
Concept.create(title: "blind dates")
Concept.create(title: "arts/crafts")
Concept.create(title: "unitards")
Concept.create(title: "chocolate")
Concept.create(title: "Donald Trump")
Concept.create(title: "chicken and waffles")
Concept.create(title: "gun ranges")
Concept.create(title: "massages")
Concept.create(title: "romance novels")
Concept.create(title: "Orange is the New Black")
Concept.create(title: "beards")
Concept.create(title: "reality TV")
Concept.create(title: "talking on the phone")
Concept.create(title: "musicals")
Concept.create(title: "Julia Childs")
Concept.create(title: "Las Vegas")
Concept.create(title: "shopping")
Concept.create(title: "beer pong")
Concept.create(title: "winter")
Concept.create(title: "recycling")
Concept.create(title: "McDonalds")
Concept.create(title: "Occupy Wall Street")
Concept.create(title: "learning a language")
Concept.create(title: "Bernie Sanders")
Concept.create(title: "traveling abroad")
Concept.create(title: "Chinese food")
Concept.create(title: "trying out new things")
Concept.create(title: "Oktoberfest")
Concept.create(title: "Valentine's Day")
Concept.create(title: "Valentine's Day all alone")
Concept.create(title: "public transportation")
Concept.create(title: "dog outfits")
Concept.create(title: "golf")
Concept.create(title: "Che Guevara")
Concept.create(title: "writing letters")
Concept.create(title: "toilet paper with the paper hanging in the front")
Concept.create(title: "gardening")
Concept.create(title: "getting blood taken")
Concept.create(title: "stand up comedy")
Concept.create(title: "writing")
Concept.create(title: "plaid shirts")
Concept.create(title: "papaya")
Concept.create(title: "painting")
Concept.create(title: "Apple computers")
Concept.create(title: "reclaimed wood")
Concept.create(title: "Napster")
Concept.create(title: "metal rock")
Concept.create(title: "Windows XP")
Concept.create(title: "brussel sprouts")
Concept.create(title: "Star Wars")
Concept.create(title: "dancing")
Concept.create(title: "tattoos")
Concept.create(title: "Silicon Valley")
Concept.create(title: "board games")
Concept.create(title: "independent film")
Concept.create(title: "zumba")
Concept.create(title: "volunteer work")
Concept.create(title: "Berkeley")
Concept.create(title: "Santa Claus")
Concept.create(title: "Head2Head")
Concept.create(title: "spin class")
Concept.create(title: "computer games")
Concept.create(title: "extreme sports")
Concept.create(title: "the Mission")
Concept.create(title: "capitalism")
Concept.create(title: "raw seafood")
Concept.create(title: "Star Trek")
Concept.create(title: "man buns")
Concept.create(title: "Volkswagon")
Concept.create(title: "France")
Concept.create(title: "brainstorming new ideas")
Concept.create(title: "casual Fridays")
Concept.create(title: "Fashion Week")
Concept.create(title: "nice guys")
Concept.create(title: "Harry Potter")
Concept.create(title: "nude beaches")
Concept.create(title: "rain storms")
Concept.create(title: "iPads")
Concept.create(title: "carwashes")
Concept.create(title: "socialism")
Concept.create(title: "listening")
Concept.create(title: "50 Shades of Gray")
Concept.create(title: "tiny houses")
Concept.create(title: "Excel modeling")
Concept.create(title: "calling mom")
Concept.create(title: "eating alone")
Concept.create(title: "tasting menus")
Concept.create(title: "peanuts")
Concept.create(title: "picnics")
Concept.create(title: "treehouses")
Concept.create(title: "HDTV")
Concept.create(title: "China")
Concept.create(title: "high school reunions")
Concept.create(title: "Empire")
Concept.create(title: "James Bond")
Concept.create(title: "Hillary Clinton")
Concept.create(title: "thinking aloud")
Concept.create(title: "preemptive war")
Concept.create(title: "Los Angeles")
Concept.create(title: "surprise birthday parties")
Concept.create(title: "flowers from a friend")
Concept.create(title: "Mean Girls")
Concept.create(title: "How to Get Away with Murder")
Concept.create(title: "singing in the shower")
Concept.create(title: "The New Yorker")
Concept.create(title: "Anthony Bourdain")
Concept.create(title: "hostels")
Concept.create(title: "fitbits")
Concept.create(title: "mindfulness")
Concept.create(title: "The Book of Mormon")
Concept.create(title: "suburbs")
Concept.create(title: "Google Glass")
Concept.create(title: "cilantro")
Concept.create(title: "star gazing")
Concept.create(title: "food fights")
Concept.create(title: "Britney Spears")
Concept.create(title: "Black Friday")
Concept.create(title: "Seinfeld")
Concept.create(title: "minimalism")
Concept.create(title: "Internet Explorer")
Concept.create(title: "scrapbooking")
Concept.create(title: "Shakespeare")
Concept.create(title: "rom coms")
Concept.create(title: "spicy food")
Concept.create(title: "volunteering")
Concept.create(title: "Grateful Dead")
Concept.create(title: "Barack Obama")
Concept.create(title: "Halloween")
Concept.create(title: "playing it safe")
Concept.create(title: "social security")
Concept.create(title: "police")
Concept.create(title: "planes")
Concept.create(title: "Edward Snowden")
Concept.create(title: "liver and onions")
Concept.create(title: "home videos")
Concept.create(title: "working with others")
Concept.create(title: "IPA beer")
Concept.create(title: "summer")
Concept.create(title: "United Nations")
Concept.create(title: "Obamacare")
Concept.create(title: "tolls on bridges")
Concept.create(title: "bars without signs out front")
Concept.create(title: "Arnold Swartzenneger")
Concept.create(title: "nacho hats")
Concept.create(title: "Calvin and Hobbes")
Concept.create(title: "beer brewing")
Concept.create(title: "ballet")
Concept.create(title: "writing poetry")
Concept.create(title: "chocolate ice cream")
Concept.create(title: "Coldplay")
Concept.create(title: "Machiovelli")
Concept.create(title: "finance")
Concept.create(title: "Jonas Brothers")
Concept.create(title: "avocados")
Concept.create(title: "NPR")
Concept.create(title: "investing")


Game.create(title: "Gryffindor")
Game.create(title: "Hufflepuff")
Game.create(title: "Ravenclaw")
Game.create(title: "Slytherin")
Game.create(title: "Stanford")
Game.create(title: "Friends")
Game.create(title: "Bay Area Youngsters - BAY")
Game.create(title: "Draw Group")
Game.create(title: "Family")
Game.create(title: "Best Study Group")
Game.create(title: "Group1")



User.create(name: "Alex", password: "password", email: "alex@email.com", image: "https://media.licdn.com/media/AAEAAQAAAAAAAAOHAAAAJDcxZTQ4NTNlLWI5ZDAtNDYyNy1hYjRhLThmMTMzZWJiMjUwOQ.jpg")
